---
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.2
  Exclude:
    - vendor/**/*
    - .vendor/**/*
