name: 🚦 CI

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.2
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rake rubocop
  unit:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        include:
          - ruby: 3.2
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run Tests
        run: bundle exec rake spec

  tests:
    needs:
      - rubocop
      - unit
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
